### ISSUE TITLE
[Feature] Clear cache from within application

### ISSUE THREAD

**Issue by SaturnusDJ** [tinderjs/tinder-desktop#21] opened 2016-04-09 09:01 UTC
A logout doesn't clear the cache fully.
I remember some people fixing problems by removing all content of the directory, including myself.
Now I see @stuwil having a problem with it.

Let's have a nice button to clear the cache, and/or at least have it done fully when logging out.

**Comment by mayeaux** [comment] 2016-04-09 13:12
Yeah I think the proper thing to do here will be to make sure that the cache is actually removed upon logout. It's _supposed_ to do that from my reading of the source but I tend to agree with you guys that the xAuthToken being cached after its already expired is causing some issues. (Educated guess)

The other thing that could probably solve the issue is having some functionality that will automatically detect and alert you if the xAuthToken is expired and prompt login again. Not sure exactly what Tinder does to invalidate existing tokens but it seems you can only have two at once and that after some amount of calls they're invalidated (but I don't have a good idea for the specifics around it).

**Comment by stuwil** [comment] 2016-04-20 06:37
Only partially resolved by #65 with proper session invalidation.

**Closed as completed** 2016-04-22 03:58 UTC
Labels: bug
